### ISSUE TITLE
三列左右栏固定中间栏边框自适应的网页布局

### ISSUE THREAD

**Issue by tvolitt** [tvolitt/bookmark#2]
# 1. flex布局
这种方法可以实现三列布局，且高度方面可以通过给`.container`设置`align-items`属性控制
```html
<div class="container">
    <div class="left">left</div>
    <div class="content">content</div>
    <div class="right">right</div>
</div>
```
```css
.container {
    display: flex;
}
.left,
.right {
    flex-basis: 100px; // 初始宽度为100px
    flex-shrink: 0; // 禁止收缩，让宽度固定
}
.content {
    flex-grow: 1; // 自动分配剩余空间
}
```
# 2. table布局
table布局可以实现三列布局，但高度固定为三列等高，可以通过给子元素设置`vertical-align`属性控制子元素内容垂直方向上的对齐方向
```html
<div class="container">
    <div class="left">left</div>
    <div class="content">content</div>
    <div class="right">right</div>
</div>
```
```css
.container {
    display: table;
    width: 100%;
}
.left,
.right {
    display: table-cell; // 关键
    width: 100px;
}
```
# 3. float布局
这种方法可以实现三列布局，但无法控制高度
```html
<div class="container">
    <div class="left">left</div>
    <div class="right">right</div>
    <div class="content">content</div>
</div>
```
```css
.container::after {
    content: "";
    display: block;
    clear: both; // 清除浮动
}
.left,
.right {
    width: 100px;
}
.left {
    float: left;
}
.right {
    float: right;
}
.content {
    margin-left: 100px;
    margin-right: 100px;
}
```
# 4. calc()函数
这种方法可以实现三列布局，但无法控制高度，calc()可以让`.content`的宽度自适应，然后就是想办法让他们放到一行里了
```html
<div class="container">
    <div class="left">left</div>
    <div class="content">content</div>
    <div class="right">right</div>
</div>
```
用`inline-block`：
```css
.container {
    font-size: 0; // 修复使用行内元素时，代码中换行符会产生空格的问题，记得要在子元素中恢复font-size
}
.container > div {
    font-size: 16px;
}
.left,
.right {
    display: inline-block;
    width: 100px;
}
.content {
    display: inline-block;
    width: calc(100% - 200px);
}
```
当然也可以用`position`定位：
```css
.container {
    position: relative;
}
.left,
.right {
    position: absolute;
    top: 0;
    width: 100px;
}
.left {
    left: 0;
}
.right {
    right: 0;
}
.content {
    position: absolute;
    left: 100px;
    width: calc(100% - 200px);
}
```
